### ISSUE TITLE
Suspected error in residential boiler baseline (BTO Market Tool)

### ISSUE THREAD

**Issue by thisIsMikeKane** [trynthink/scout#180] opened 2017-02-25 03:45 UTC
I suspect there might be an error in the calculation of the the total market size for All Residential Boiler Heating by Fuel Use using the [BTO Market Tool](https://trynthink.github.io/scout/calculator.html). Specifically, the tool calculates 762.6 TBtu of energy use in 2016 from all residential **boilers** running on _**electricity**_? How is the calculation substantiated? I cannot find any information in the AEO regarding residential electric boilers. Additionally, my market intuition tells me that the market for all residential gas and oil boilers should larger than electric boilers, not less as the tool calculates (476.3 TBtu and 232.1 TBtu respectively).

Thank you for working hard developing Scout and continuing to make this a valuable tool to the community.

**Comment by jtlangevin** [comment] 2017-03-06 23:11
@thisIsMikeKane: Thanks very much for pointing this potential issue out. Upon further investigation of the EIA data from which these numbers were generated, it looks like on a _primary energy_ basis, EIA projects more residential electric boiler energy in 2016 than residential gas and oil boiler energy, (based on a site-source energy conversion of about 3X for electricity). The EIA data also show more residential electric boiler units on the market than gas and oil boiler units (28 million vs. 11 and 4 million, respectively).

We get these data as raw .txt files from the EIA. The specific data you're referencing come from the 'RESDBOUT.txt' file. You'll be able to find some detail about the modeling methods in the EIA [Residential NEMS documentation](https://www.eia.gov/outlooks/aeo/nems/documentation/residential/pdf/m067(2014).pdf), but let me know if you'd like to find out more and I can put you in touch with the right individual.

**Comment by thisIsMikeKane** [comment] 2017-03-07 01:08
@jtlangevin Thanks for the detailed description, and also the thoroughness of your documentation and rigorous development of Scout, I'm quite impressed.

I looked into the EIA Residential NEMS documentation, and didn't find any information about electric boilers. Table 1 only lists Fuel Oil and Natural Gas as fuels for boiler based space heating. A Google search of eia.gov returns mainly information regarding commercial electric boilers, and a brief statement that no standard exists for residential boilers. These observations, and the lack even a mention of residential electric boilers in the RECS dataset are what led me to question the BTO Market Tool in the first place. Unfortunately, I don't have access to the NEMs data yet, so I can't investigate this further. I hope my observations so far are at least useful. 

Thanks again for helping investigate this issue, even if it ends up being an issue with the EIA data for this corner case and not Scout.

**Comment by jtlangevin** [comment] 2017-03-07 02:14
@thisisMikeKane: Good observations, thanks. I'll reach out to EIA to see if I can get a better answer on what's going on.

**Comment by thisIsMikeKane** [comment] 2017-03-07 03:00
Thanks!

**Comment by thisIsMikeKane** [comment] 2017-03-10 05:28
I got the data from EIA, and I think I figured it out. Scout classifies the EIA variable `ELEC_RAD` as `'boiler (electric)'` on `line 127` of `mseg.py`. I don't have the variable definition file from EIA, but if I had to guess, I'd say that `ELEC_RAD` represents pure electric radiators, i.e. Joule heating at the point of radiation, not electricity boiling water that is pumped through hydronic radiators. Do you have access to the EIA variable definition file to confirm?

**Comment by jtlangevin** [comment] 2017-03-10 13:03
That's entirely possible, I will confirm with EIA ASAP. Sorry, it's been a busy week!

**Comment by jtlangevin** [comment] 2017-03-22 13:20
@thisIsMikeKane: I believe you already figured this out, but EIA confirmed your suspicion that 'ELEC_RAD' means radiator heating, not electric boiler heating. I will modify our data dictionary in 'ecm_prep.py' accordingly and close this issue once that modification is committed. We are also in the process of updating to AEO 2017 baseline data, and I'll be sure that those data are generated with this fix implemented.

Many thanks for letting us know about the issue and for your diligence in tracking down the source of the error.

**Comment by thisIsMikeKane** [comment] 2017-03-22 16:44
@jtlangevin Yup, sounds like we have a good solution. Thanks for looking into this for me. Best of luck.

**Comment by trynthink** [comment] 2017-04-05 19:21
The Market Calculator website is now updated to correctly describe the "ELEC_RAD" coded AEO data as electric resistance heating. Modifications to make this change permanent for future data updates are committed now and will eventually be reflected on the master branch.

**Closed by trynthink** 2017-04-05 19:21 UTC
Labels: bug, calculator, database
